version: "3.9"
services:
  dev:
    build:
      context: ./repo1
      dockerfile: ./dockerdev
    container_name: dev
    volumes:
      - ./src:/app
    networks:
      - development
  prod1:
    build:
      context: ./repo2
      dockerfile: ./dockerprod1
    container_name: prod1
    volumes:
      - ./src:/app
    networks:
      - production
  prod2:
    build:
      context: ./repo3
      dockerfile: ./dockerprod2
    container_name: prod2
    volumes:
      - ./src:/app
    networks:
      - production
networks:
  development:
  production:
